# Generated by Django 4.0.1 on 2022-11-27 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_privatequestion_privatelesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatelesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.privatesubject'),
        ),
        migrations.AlterField(
            model_name='privatequestion',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.privatelesson'),
        ),
    ]
